# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  #- "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "https://github.com/sambitpal001/reference-producer"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "master"
    git: "github"
    stage: "clone"

  #build:
  #  title: "Building Docker image"
  #  type: "build"
  #  image_name: "sambitpal001/reference-producer"
  #  working_directory: "${{clone}}"
  #  tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
  #  dockerfile: "Dockerfile"
  #  stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "maven:3.5.2-jdk-8-alpine" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository test
    stage: "test"